# -*- mode: org; mode: auto-fill; fill-column: 80 -*-

#+TITLE: Create a Reasonable Introduction Mechanism
#+OPTIONS:   d:t
#+LINK_UP:  ./
#+LINK_HOME: ../

* Issue

  It's pretty difficult to introduce folks to one another right now.  The
  requirements aren't even written down anywhere.

* Fixes [0/2]

   KISS: export and import minimum data required to make this work.  That sounds
   like the PGP key and the connector locations.

   How do we decide which locations should be exported for which keys?  Is there
   a default list of services or something?  Maybe I just specify the locations
   or pick somebody else's key to copy.

   How are the data laid out after export?  The whole mess (or at least the
   location data) must be signed by the exported key.  Maybe just a good old
   archive for two separate files: the public key and the signed locations.
   That's about as simple as we can keep it.

** TODO Functional Requirements [0/4]

*** TODO Export Required Data

    - [ ] PGP Public Key

    - [ ] FreedomBuddy Locations

*** TODO Secure Exported Data

    - [ ] PGP Sign the data.

*** TODO Import Required Data

    - [ ] PGP Public Key

    - [ ] FreedomBuddy Locations

*** TODO Verify Imported Data

    - [ ] Import the public key and verify that the statement was signed by the
          key.  Reject the statement if not.

** TODO Tests [0/1]

*** TODO Round trip data

    If I export data, is it imported in the same state it was when it was
    exported?  We'll need separate FBuddies for each (otherwise the source would
    reject its own data because of the non-new timestamp).

    When FBuddy locations for X are exported by one server and then imported by
    another, does that other server know of those same locations?

* Discussion

* Metadata
  :PROPERTIES:
  :Status:   Incomplete
  :Priority: 0
  :Owner:    Nick Daly
  :Tags:
  :Description:     Create Introduction Mechanism
  :END:
